### ISSUE TITLE
Better Officer Bios

### ISSUE THREAD

**Issue by rambleraptor** [csescholarsum/csescholarsum.github.io#2]
Something that sounds more professional and advertises us better.

**Comment by sartechb** [comment]
Not exactly fixed but is affected by #10

**Comment by rambleraptor** [comment]
Do you need admin access to this account + repo?

Get Outlook for iOS

On Sat, Oct 1, 2016 at 10:28 AM -0700, "Sarthak Bhandari" notifications@github.com wrote:

Not exactly fixed but is affected by #10

**Comment by sartechb** [comment]
Nah, Taku has it

## 

Sarthak Bhandari

Sent from
https://polymail.io/?utm_source=polymail&utm_medium=referral&utm_campaign=signature

On Sun, Oct 02, 2016 at 12:30 AM Alex Stephen

<
mailto:Alex Stephen notifications@github.com

> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Do you need admin access to this account + repo?

Get Outlook for iOS

On Sat, Oct 1, 2016 at 10:28 AM -0700, "Sarthak Bhandari" notifications@github.com wrote:

Not exactly fixed but is affected by #10

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or mute the thread.

—

You are receiving this because you commented.

Reply to this email directly,
https://github.com/csescholarsum/csescholarsum.github.io/issues/2#issuecomment-250953081
, or
